### ISSUE TITLE
Conflict with colour confirmation addon

### ISSUE THREAD

**Issue by TowelSniffer** [phu54321/anki_plugins#20]
I seem to be getting a conflict with the colour confirmation addon  https://ankiweb.net/shared/info/1084228676

```
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-12 16:29:02

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 368, in handler
  File "aqt\reviewer.py", line 322, in _onAnswerButton
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-116>", line 2, in _answerCard
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 525, in repl
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-20>", line 2, in _answerCard
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\1508357010\RemainingTime.py", line 34, in _newAnswerCard
    ret = _old(self, ease)
  File "aqt\reviewer.py", line 262, in _answerCard
  File "aqt\gui_hooks.py", line 720, in __call__
  File "C:\Users\fionn\AppData\Roaming\Anki2\addons21\1084228676\__init__.py", line 164, in answerCard_after
    ivl = str(round(msg/30.44, 1)) + " months"; # convert days to months
TypeError: unsupported operand type(s) for /: 'str' and 'float'
```

**Comment by phu54321** [comment]
this is a problem of that addon. not directly related to this addon.
