### ISSUE TITLE
Error in the automatic switch from basic to cloze addon

### ISSUE THREAD

**Issue by FiniTea** [phu54321/anki_plugins#5]
Hey there!

The addon doesnt work for me, i get this error:

Traceback (most recent call last):
  File "anki/hooks.pyc", line 61, in repl
  File "/Users/Fin/Library/Application Support/Anki2/addons/cloze_overlapper/main.py", line 256, in onAddCards
    return _old(self)
  File "anki/hooks.pyc", line 61, in repl
  File "/Users/Fin/Library/Application Support/Anki2/addons/Automatic_switch_from_Basic_to_Cloze.py", line 71, in newAddCards
    change_model_to(self.modelChooser, cloze_note_type)
  File "/Users/Fin/Library/Application Support/Anki2/addons/Automatic_switch_from_Basic_to_Cloze.py", line 48, in change_model_to
    chooser.deck.conf['curModel'] = m['id']
TypeError: 'NoneType' object has no attribute '__getitem__'

i am on mac 10.14 mojave with the latest version of ankis stable.

Is there a way to fix that?

**Comment by phu54321** [comment]
2. How is the cloze model named? (In your language as-is)
-----Original Message-----
보낸사람: "FiniTea" <notifications@github.com>
받는사람: "phu54321/anki_plugins" <anki_plugins@noreply.github.com>
참조: "Subscribed" <subscribed@noreply.github.com>
날짜: 2018.10.04 오후 08:00:28
제목: [phu54321/anki_plugins] Error in the automatic switch from basic to cloze addon (#5)

Hey there!
The addon doesnt work for me, i get this error:
Traceback (most recent call last):
File "anki/hooks.pyc", line 61, in repl
File "/Users/Fin/Library/Application Support/Anki2/addons/cloze_overlapper/main.py", line 256, in onAddCards
return _old(self)
File "anki/hooks.pyc", line 61, in repl
File "/Users/Fin/Library/Application Support/Anki2/addons/Automatic_switch_from_Basic_to_Cloze.py", line 71, in newAddCards
change_model_to(self.modelChooser, cloze_note_type)
File "/Users/Fin/Library/Application Support/Anki2/addons/Automatic_switch_from_Basic_to_Cloze.py", line 48, in change_model_to
chooser.deck.conf['curModel'] = m['id']
TypeError: 'NoneType' object has no attribute 'getitem'
i am on mac 10.14 mojave with the latest version of ankis stable.
Is there a way to fix that?

**Comment by phu54321** [comment]
1. What is your language?
2. How is the cloze model named? (In your language as-is)

**Comment by phu54321** [comment]
Closing due to inactivity... Cannot reproduce
